name: ws
description: >
  WS is a powerful, cross-platform library designed to facilitate the implementation of WebSocket clients in various software applications.
  This library provides a simple, high-level API, enabling developers to establish, maintain, and manage WebSocket connections efficiently.
version: 0.0.3-dev.placeholder
homepage: https://github.com/plugfox/ws
repository: https://github.com/plugfox/ws
issue_tracker: https://github.com/plugfox/ws/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
